### ISSUE TITLE
Calibre-web 权限问题，上传书籍出错

### ISSUE THREAD

**Issue by xhan** [gshang2017/docker#142]
Calibre-web 上传书籍会报错，但用Calibre-Server就没问题。
错误提示：
> 将标题从“/tmp/calibre_web/c3b8416a0ab862b37fdcd7693a5ee679”改为“/library/Cheng Nien/Life and Death in Shanghai (3)”时失败，出错信息：[Errno 1] Operation not permitted: '/library/Cheng Nien/Life and Death in Shanghai (3)/Life and Death in Shanghai.epub'

检查目录发现文件夹已经创建成功：

> ls
> 'Life and Death in Shanghai'  'Life and Death in Shanghai (3)'

但是书籍没有正确被移动到目标文件夹内

检查日志，有一堆权限问题：

> spawn calibre-server --userdb /config/calibre-server/server-users.sqlite --manage-users
> 2) Edit an existing user
> 1) Add a new user
> chown: /config/calibre-server/plugins: Operation not permitted
> chown: /config/calibre-server/caches: Operation not permitted
> chown: /config/calibre-server: Operation not permitted
> chown: /config/calibre-web/client_secrets.json: Operation not permitted
> chown: /config/calibre-web: Operation not permitted
> chown: /config/calibre-web/app.db: Operation not permitted
> What do you want to do? [1-4]: 1
> Enter the username: calibre
> The username calibre already exists
> 4) Cancel
> 3) Remove a user

启动环境：

```
version: "1.0"
services:
  calibreweb:
    image: johngong/calibre-web
    container_name: calibreweb
    environment:
      - PUID=0
      - PGID=0
      - DOCKER_MODS=johngong/calibre-web:calibre
      - CALIBRE_SERVER_USER=calibre
      - CALIBRE_SERVER_PASSWORD=calibre
    volumes:
      - /srv/dev-disk-by-uuid-631A-A46B/calibre/config:/config
      - /srv/dev-disk-by-uuid-631A-A46B/calibre/books:/library
      - /srv/dev-disk-by-uuid-631A-A46B/calibre/autoaddbooks:/autoaddbooks
    ports:
      - 8083:8083
      - 8080:8080
    restart: unless-stopped
```
