### ISSUE TITLE
qBittorrent EE 重启容器后就恢复成非EE版本, 且丢失webui的配置

### ISSUE THREAD

**Issue by jqtmviyu** [gshang2017/docker#175]
版本: 4.5.0. 4.5.0.10
问题描述: 重启容器后变成非ee版本, 且丢失配置(包括端口,webui密码)

docker-compose.yml

```yml
version: "3.9"
services:

  qBittorrent:
    image: johngong/qbittorrent:latest
    container_name: qBittorrent
    ports:
      - 8989:8989 # 两者需与下方的QB_WEBUI_PORT一项完全一致
      - 6881:6881/udp
      - 6881:6881
    environment:
      - PUID=0
      - PGID=0
      - QB_WEBUI_PORT=8989
      - QB_TRACKERS_UPDATE_AUTO=true
      - QB_TRACKERS_LIST_URL=https://cdn.jsdelivr.net/gh/DeSireFire/animeTrackerList/AT_all.txt  # 改成动漫类的
      - QB_EE_BIN=true
    volumes:
      - ./qb:/config
      - ./Downloads:/Downloads
    restart: unless-stopped
```
