### ISSUE TITLE
是否能在host网络模式下运作

### ISSUE THREAD

**Issue by timmyhbk** [gshang2017/docker#177]
因为希望能使用IPv6，尝试用`network_mode: host`运行，但无法开启WebUI。
请问是否有机会在host下运行?谢谢。

docker-compose：
````
version: '3.3'
services:
    qbittorrent:
        container_name: qbittorrent
        environment:
            - QB_WEBUI_PORT=8087
            - QB_EE_BIN=false
            - PUID=1026
            - PGID=100
            - UMASK=022
        volumes:
            - '/volume1/docker/qbittorrent:/config'
            - '/volume1/download/bt:/Downloads'
        restart: unless-stopped
        image: 'johngong/qbittorrent:latest'
        network_mode: host
````
