### ISSUE TITLE
请问 calibre-web 中有哪个进程每隔1秒产生一次磁盘访问，启动容器后硬盘总是一秒响一次，吵得人烦躁

### ISSUE THREAD

**Issue by BeMxself** [gshang2017/docker#249]
我在nas上安装了 calibre-web 总是会咯哒咯哒响，吵得我头疼。
我尝试过：
- 删除`/etc/inotify`并重启，重启后进入容器确认没有inotify相关进程了
- 禁用自动重启选项 `CALIBRE_SERVER_RESTART_AUTO=false`

均未生效。

然后我换了 linuxserver/calibre-web 的镜像，这个镜像就没有噪音。

我对比了一下 linuxserver/calibre-web 的进程，除了inotify相关的进程以外没看出什么两样的：

这是使用本镜像时，我干掉 inotify 之前的进程截图
<img width="739" alt="image" src="https://github.com/user-attachments/assets/58298a1c-7798-451c-91fd-ee802620099b">

这是 linuxserver/calibre-web 的进程截图
<img width="596" alt="image" src="https://github.com/user-attachments/assets/08f14f96-feef-4430-82a8-bab0f3497044">

这个镜像各方面都很完美，但就是这个1秒1次的响声实在让人崩溃。

**Comment by gshang2017** [comment]
可能是未配置calibre-server服务导致s6一直在试图启动此服务，你可以试下开启  ENABLE_CALIBRE_SERVER=true 测试下。

**Comment by BeMxself** [comment]
> 可能是未配置calibre-server服务导致s6一直在试图启动此服务，你可以试下开启 ENABLE_CALIBRE_SERVER=true 测试下。

感谢回复，试了下最新的镜像，然后用如下docker-compose.yml启动:
```yml
services:
  calibre-web:
    image: dockerproxy.net/johngong/calibre-web
    container_name: calibre-web
    environment:
      - UID=1000
      - GID=1000
      - ENABLE_CALIBRE_SERVER=true
      - CALIBRE_SERVER_USER=xxxx
      - CALIBRE_SERVER_PASSWORD=xxxx
      - CALIBRE_SERVER_RESTART_AUTO=false
      - ENABLE_AUTOADDBOOKS=false
    volumes:
      - /volume1/docker/calibre:/config
      - /volume1/docker/calibre/Library:/library
      - /volume1/docker/calibre/AutoAdd:/autoaddbooks
    ports:
      - 7080:8083
    restart: unless-stopped
```

1秒1读的情况没有了，现在变成大约5秒一读的样子😂
